# Pure lambda caclulus:

term = application
     | LAMBDA IDENTIFIER "." term

application = atom application^

application^ = atom application^
            | #Empty

atom = "(" term ")"
     | IDENTIFIER