program     = (definition NEWLINE)* term 'EOF' ;

definition  = "let" IDENTIFIER "=" term ;

term        = application
            | "\" IDENTIFIER "." term ;

application = atom application
            | ; (*Empty*) 

atom        = "(" term ")"
            | IDENTIFIER ;